### PR TITLE
Update circle.yml - fix tests

### PR DESCRIPTION
**Pull request by sanchothefat**
Sync submodules, currently fails to checkout WP

### CODE REVIEW

**Comment by BronsonQuick** [comment]
@rmccue Got any ideas why CircleCI is throwing this error:
```
fatal: reference is not a tree: d48ec22bd29af54662d32904978678fbf102705d
Unable to checkout 'd48ec22bd29af54662d32904978678fbf102705d' in submodule path 'wordpress'

git submodule update --init --recursive returned exit code 1

Action failed: git submodule update --init --recursive
```

I've tried pinning the wordpress submodule to branches and SHA's but CircleCI always throws `fatal: reference is not a tree:` error

**Comment by sanchothefat** [comment]
I was about to had to switch project - you can run the ci build with ssh
then poke about the machine. You could check the submodule is pointing to
the right place in gitmodules and the checkout itself

-- 
*Robert O'Rourke*
Senior WordPress Engineer
humanmade

*phone: *+447816329424
*email:* rob@hmn.md
*skype:* rob.o.rourke
*twitr:* @sanchothefat <https://twitter.com/sanchothefat>

**Comment by BronsonQuick** [comment]
@sanchothefat Cool. Taa. SSH helped! CircleCI has cached `.git/modules/wordpress` when I manually remove that and run `git submodule update --init` it checks out. Running CircleCI without caching didn't fix that up. Just gotta read the docs on how to trigger the build manually in SSH and we should be good!

**Comment by BronsonQuick** [comment]
@sanchothefat 🎉 FYI if this happens again with submodules this is the fix! https://github.com/humanmade/hm-base/pull/38/commits/6cea416f9e13200cfb09cb7b27c7471863d8db7f

**Pull request merged**
