### PR TITLE
Login redirect bug

### PR DESCRIPTION
**Pull request by mattheu**
I have an issue where I go to `site.dev/wp-admin` and get redirected to `site.dev/wordpress/wp-admin` which is great... except that `reauth=1` gets appended to the url. Which causes a logout as soon as I try and log in.

We should probably be handleing this at the level that the redirect is happening - but I can't for the life of me work out where this is... 

I noticed Joel was experiencing this issue too - although he had got pretty used to it and always remembered to remove the query args from the url.

### CODE REVIEW

**Comment by pdewouters** [comment]
Would be nice to fix, as clients often contact us complaining that they're unable to log in. Had that a lot with Yell

**Comment by sanchothefat** [comment]
@pdewouters @mattheu see https://github.com/humanmade/Salty-WordPress/pull/132 - we have one configuration for subdomain multisite and another for subfolder, this normalises that and fixed the problem for me at least in that situation.

**Comment by pdewouters** [comment]
Ah yes I applied that for working on the ADoR site.

**Comment by owaincuvelier** [comment]
Bump!

**Comment by rmccue** [comment]
Closing this, please reopen if it's still relevant!

**Pull request closed without merging**
